# Generated by Django 4.2.27 on 2025-12-04 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_coche_imagen_detalle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_finalizacion',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_inicio',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='codigo_promocion',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='updated',
        ),
        migrations.AddField(
            model_name='reserva',
            name='coche',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrador.coche'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
