# Generated by Django 4.2.27 on 2025-12-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_rename_fecha_finalizacion_reserva_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coche',
            name='imagen',
        ),
        migrations.AddField(
            model_name='coche',
            name='imagen_catalogo',
            field=models.ImageField(default=1, upload_to='coches/catalogo/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coche',
            name='imagen_top10',
            field=models.ImageField(default=1, upload_to='coches/top10/'),
            preserve_default=False,
        ),
    ]
