# Generated by Django 5.2.6 on 2025-12-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_remove_coche_imagen_coche_imagen_catalogo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valoracion', models.DecimalField(decimal_places=1, max_digits=3)),
                ('categoria', models.CharField(choices=[('deportivo', 'Deportivo'), ('electrico', 'Eléctrico'), ('lujo', 'Lujo')], default='deportivo', max_length=50)),
                ('imagen_catalogo', models.ImageField(blank=True, null=True, upload_to='catalogo/')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
