# Generated by Django 5.0.6 on 2025-12-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_remove_coche_imagen_coche_imagen_catalogo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('alcance', models.CharField(max_length=50)),
                ('velocidad', models.CharField(max_length=50)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to='autos/')),
            ],
        ),
    ]
