# Generated by Django 5.0.6 on 2025-12-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_auto'),
        ('administrador', '0005_comentario_promocion'),
    ]

    operations = [
    ]
