# Generated by Django 5.2.6 on 2025-12-04 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_catalogo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catalogo',
        ),
    ]
