# Generated by Django 5.2.6 on 2025-12-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_delete_catalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coche',
            name='categoria',
            field=models.CharField(choices=[('DEPORTIVO', 'Deportivo'), ('ELECTRICO', 'Eléctrico'), ('LUJO', 'Lujo')], default='DEPORTIVO', max_length=20),
        ),
    ]
