# Generated by Django 5.2.6 on 2025-12-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_merge_0005_auto_0005_comentario_promocion'),
        ('administrador', '0007_coche_categoria'),
    ]

    operations = [
    ]
